### ISSUE TITLE
Missing TSTools.h file.

### ISSUE THREAD

**Issue by JesseRMeyer** [EricLengyel/Terathon-Container-Library#1]
Hi, `TSTools.h` is included but not part of the repository.

https://github.com/EricLengyel/Terathon-Container-Library/blob/f987b6d0186ea16536f6653861330e3731b0f636/TSHash.cpp#L11

**Comment by EricLengyel** [comment]
Thanks for pointing that out. I removed the dependency on TSTools.h. Separately, I noticed that TSBasic.h was needed elsewhere, so that file has been added.
