### ISSUE TITLE
Confirmation of email message receipt

### ISSUE THREAD

**Issue by ericmelse** [EricLengyel/Terathon-Container-Library#2]
Dear Dr Lengyel,

On 13-2-2024 17:37 I wrote you an email about your Slug Algorithm, library and font editor.
Did you receive this email?
If you did not receive it I can resend my message or post it here.

Time permitting, I appreciate to receive your answer to my questions.
 
Best regards,
Eric Melse
 
The Netherlands

**Comment by EricLengyel** [comment]
Your email was received, and it's in the queue with a lot of others that I need to respond to.
